// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'dart:convert';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/services.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  late FirebaseOptions web;
  late FirebaseOptions android;
  late FirebaseOptions ios;

  Future<DefaultFirebaseOptions> init() async {
    final data = await FirebaseRuntimeOptions().read();
    web = const FirebaseOptions(
      apiKey: String.fromEnvironment('API_KEY'),
      appId: String.fromEnvironment('API_ID'),
      messagingSenderId: String.fromEnvironment('SENDER_ID'),
      projectId: String.fromEnvironment('PROJ_ID'),
      authDomain: String.fromEnvironment('DOMAIN'),
      storageBucket: String.fromEnvironment('BUCKET_NAME'),
      measurementId: String.fromEnvironment('MEAS_ID'),
    );

    android = const FirebaseOptions(
      apiKey: String.fromEnvironment('API_KEY'),
      appId: String.fromEnvironment('API_ID'),
      messagingSenderId: String.fromEnvironment('SENDER_ID'),
      projectId: String.fromEnvironment('PROJ_ID'),
      storageBucket: String.fromEnvironment('BUCKET_NAME'),
    );

    ios = const FirebaseOptions(
      apiKey: String.fromEnvironment('API_KEY'),
      appId: String.fromEnvironment('API_ID'),
      messagingSenderId: String.fromEnvironment('SENDER_ID'),
      projectId: String.fromEnvironment('PROJ_ID'),
      storageBucket: String.fromEnvironment('BUCKET_NAME'),
      iosClientId: String.fromEnvironment('IOS_CLIENT_ID'),
      iosBundleId: String.fromEnvironment('IOS_BUNDLE_ID'),
    );

    return this;
  }

  FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}

class FirebaseRuntimeOptions {
  factory FirebaseRuntimeOptions() {
    return _instance;
  }

  FirebaseRuntimeOptions._internal();

  static final FirebaseRuntimeOptions _instance =
      FirebaseRuntimeOptions._internal();

  Future<dynamic> read() async {
    final raw = await rootBundle.loadString('assets/firebase_config.json');
    return await json.decode(raw);
  }
}
